version: '3.3'
services:
    apache-example:
      container_name: php
      build: ./php
      depends_on:
        - db
      ports:
        - 80:80
      volumes:
        - ./src:/var/www/html
      networks:
        - network
    
    db:
      container_name: db
      image: mariadb:10.3
      ports:
        - 3306:3306
      command:
       - --innodb-buffer-pool-size=45MB
      volumes:
       - mysql:/var/lib/mysql
       - ./persons.sql:/docker-entrypoint-initdb.d/persons.sql 
      restart: always
      environment:
        MYSQL_DATABASE: "aNewBegening"
        MARIADB_AUTO_UPGRADE: 1
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "root"
        MYSQL_ROOT_PASSWORD: "root"
      networks:
        - network
    
networks:
  network:
    driver: bridge

volumes:
  mysql:
